<?php

namespace BulveyzRouter;

/**
 * Class Route
 * @package App
 */
class Route extends RouteCollection
{

    /**
     * @var
     * Содержит имя маршрута
     */
    public static $setName;


    /**
     * @var
     * Содержит метод маршрута
     */
    public static $method;

    /**
     * @param $route
     * @param null $callback
     * @return Route
     */
    public static function get($route, $callback = null)
    {
        self::addRoute($route, $callback, 'GET');
        self::$setName = $route;
        self::$method = 'GET';
        return new static();
    }

    /**
     * @param $route
     * @param null $callback
     * @return static
     */
    public static function post($route, $callback = null)
    {
        self::addRoute($route, $callback, 'POST');
        self::$setName = $route;
        self::$method = 'POST';
        return new static();
    }

    /**
     * @param $route
     * @param null $callback
     * @return static
     */
    public static function any($route, $callback = null)
    {
        self::addRoute($route, $callback, 'ANY');
        self::$setName = $route;
        self::$method = 'ANY';
        return new static();
    }

    public static function put($route, $callback = null)
    {
        self::addRoute($route, $callback, 'PUT');
        self::$setName = $route;
        self::$method = 'PUT';
        return new static();
    }

    public static function path($route, $callback = null)
    {
        self::addRoute($route, $callback, 'PATH');
        self::$setName = $route;
        self::$method = 'PATH';
        return new static();
    }

    /**
     * @return array
     * Возвращает массив маршрутов
     */
    public static function routeList()
    {
        return self::$routes;
    }

    /**
     * @param $newName
     * Устанавливает имя для маршрута
     */
    public static function name($newName)
    {
        parent::setName($newName, self::$setName, self::$method);
    }

    /**
     * @param string $namespace
     * Изменяет пространтсво имен для контроллеров
     */
    public static function setNamespace($namespace)
    {
        parent::setNamespace($namespace); // TODO: Change the autogenerated stub
    }
}